name: ziggurat
version: 0.5.0
description: >
  A library for making audio games.

  This package started out as a way to create 2d maps for use in games, but has
  since grown to include tools and methods for making audio games with and
  without maps.
repository: https://github.com/chrisnorman7/ziggurat

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.2.0
  dart_sdl: ^0.3.0
  encrypt: ^5.0.0
  json_annotation: ^4.1.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.0.6
  json_serializable: ^5.0.0
  lints: ^1.0.0
  test: ^1.16.0

executables:
  encrypt-folder: encrypt_folder
  ls-vault: ls_vault
