name: ziggurat
version: 0.50.2
description: >
  A library for making fully-featured audio games using Dart and SDL.
repository: https://github.com/chrisnorman7/ziggurat
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_sdl: ^0.10.0
  dart_synthizer: ^0.11.0
  encrypt: ^5.0.1
  json_annotation: ^4.6.0
  meta: ^1.8.0
  path: ^1.8.2

dev_dependencies:
  analyzer: ^4.2.1
  build_runner: ^2.2.0
  build_test: ^2.1.5
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.21.4
