publish_to: none
name: ziggurat
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.0-301.0.dev <3.0.0"

dependencies:
  dart_synthizer:
    git: https://github.com/chrisnorman7/dart_synthizer
  meta: ^1.7.0
  spatialhash:
    git:
      url: https://github.com/chrisnorman7/spatialhash.git
      ref: chrisnorman7/issue1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
