name: ziggurat
version: 0.43.0
description: >
  A library for making fully-featured audio games using Dart and SDL.
repository: https://github.com/chrisnorman7/ziggurat
environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dart_sdl: ^0.9.5
  encrypt: ^5.0.1
  json_annotation: ^4.4.0
  meta: ^1.7.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^2.1.7
  build_test: ^2.1.5
  json_serializable: ^6.1.4
  lints: ^1.0.1
  test: ^1.20.1
