publish_to: none
name: ziggurat
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.0-301.0.dev <3.0.0"

dependencies:
  args: ^2.2.0
  dart_synthizer:
    git: https://github.com/chrisnorman7/dart_synthizer
  encrypt: ^5.0.0
  json_annotation: ^4.1.0
  meta: ^1.7.0
  spatialhash:
    git:
      url: https://github.com/chrisnorman7/spatialhash.git
      ref: chrisnorman7/issue1

dev_dependencies:
  build_runner: ^2.0.6
  json_serializable: ^5.0.0
  lints: ^1.0.0
  test: ^1.16.0

executables:
  encrypt-folder: encrypt_folder
  ls-vault: ls_vault
