name: ziggurat
version: 0.58.0
description: >
  A library for making fully-featured audio games using Dart and SDL.
repository: https://github.com/chrisnorman7/ziggurat
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  dart_sdl: ^0.10.0
  dart_synthizer: ^0.11.1
  encrypt: ^5.0.1
  file: ^6.1.4
  json_annotation: ^4.8.0
  meta: ^1.8.0
  path: ^1.8.2

dev_dependencies:
  build_runner: ^2.3.2
  build_test: ^2.1.5
  json_serializable: ^6.5.4
  lints: ^2.0.1
  test: ^1.22.0
