name: ziggurat
version: 0.44.0
description: >
  A library for making fully-featured audio games using Dart and SDL.
repository: https://github.com/chrisnorman7/ziggurat
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_sdl: ^0.10.0
  encrypt: ^5.0.1
  json_annotation: ^4.5.0
  meta: ^1.7.0
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.1.10
  build_test: ^2.1.5
  json_serializable: ^6.2.0
  lints: ^2.0.0
  test: ^1.21.1
