name: ziggurat
version: 0.61.0
description: >
  A library for making fully-featured audio games using Dart and SDL.
repository: https://github.com/chrisnorman7/ziggurat
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  dart_sdl: ^0.10.1
  dart_synthizer: ^0.11.2
  encrypt: ^5.0.1
  json_annotation: ^4.8.0
  meta: ^1.9.0
  path: ^1.8.3

dev_dependencies:
  build_runner: ^2.3.3
  json_serializable: ^6.7.0
  lints: ^2.0.1
  test: ^1.24.0
