name: ziggurat
version: 0.28.0
description: >
  A library for making fully-featured audio games using Dart and SDL.
repository: https://github.com/chrisnorman7/ziggurat

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  dart_sdl: ^0.8.6
  encrypt: ^5.0.1
  json_annotation: ^4.4.0
  meta: ^1.7.0
  path: ^1.8.1

dev_dependencies:
  build_runner: ^2.1.7
  build_test: ^2.1.5
  json_serializable: ^6.1.3
  lints: ^1.0.1
  test: ^1.20.1
